#!/bin/bash

SCRIPT_DIR=$(cd "$(dirname "$0")"; pwd)
source "${SCRIPT_DIR}/helpers.sh"
source "${SCRIPT_DIR}/shared.sh"

function restore_archive() {
  check_path_restore $2

  $duplicity --progress \
    --verbosity info \
    --cf-backend swift \
    --log-file ${LOGFILE_RESTORE} \
    "swift://$1" "${2}"
}

function restore_archive_from_local() {
  check_path_restore $2

  $duplicity --progress \
    --verbosity info \
    --log-file ${LOGFILE_RESTORE} \
    "file://$1" "${2}"
}

function restore_file() {
  check_path_restore $3

  $duplicity --progress \
    --verbosity info \
    --cf-backend swift \
    --log-file ${LOGFILE_RESTORE} \
    --file-to-restore "${2}" \
    ${OPT_DRY_RUN} \
    "swift://$1" "${3}"
}

# restore_archive_from_local ${FULL_BACKUP_DIR}/home /tmp/restoration
# restore_file home .backup/exclude-list-duplicity-home.txt /tmp/restore
# restore_archive home /Users/colin/.backup/restoration
restore_file home code/imparato/.google-deploy-key.json /tmp/restore
